name: 2-minute-cron
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call Hej Job API route
        run: |
          curl --request POST \
          --url 'https://hej-margostino.vercel.app/api/job' \
          --header 'Authorization: Bearer ${{ secrets.HEJ_JOB_SECRET }}'
